### ISSUE TITLE
.csv result 

### ISSUE THREAD

**Issue by 307509256** [bendidi/Tracking-with-darkflow#12]
1. bug1
![bug](https://user-images.githubusercontent.com/5523697/32165834-0521d3ec-bd9f-11e7-8548-410bf9fb91bd.png)

track_id  from 7 to 18?  may be is 8?

---
2. bug2
![bug2](https://user-images.githubusercontent.com/5523697/32165911-3ad2b01a-bd9f-11e7-81a0-0816dbbaf0d4.png)
x is -59?

**Comment by bendidi** [comment]
thanks for reporting the bugs !

* For the first one , yeah it should be 8 normally , it should be a bug in the original deep_sort  implementation (assuming you used deep-sort ), I'll try to look into it , or I'll ask the original author if I don't find anything

* The second bug, I'll be pushing a fix some time later , but basically it's just limiting x,y,w,h to 0/maxWidth or maxHeight , I'm already doing that for visualization , just forgot to add it for the csv too

**Comment by 307509256** [comment]
Thank you for your feedback. I use deep_sort .
may be the sort num ("count : ")can be display in the video , like this
![sort](https://user-images.githubusercontent.com/5523697/32357493-3b976ece-c078-11e7-9c9f-10064826d71c.jpg)

**Comment by 307509256** [comment]
@bendidi  what is different between sort and deep_sort?

**Comment by bendidi** [comment]
deep_sort is build upon sort , it uses deep encoders to build features for each detected box and match it with it's corresponding box in next frame, I've put links to both of them in the readme file , you can find more info there
