### ISSUE TITLE
How to save the video tracked with the bounding boxes?

### ISSUE THREAD

**Issue by sathishmanivannan** [bendidi/Tracking-with-darkflow#13]

**Comment by seovchinnikov** [comment]
Ive made a PR that was merged (https://github.com/bendidi/darkflow/pull/2) so now it should save video with boxes

**Comment by sathishmanivannan** [comment]
Even after changing the predict.py and the run.py with the FLAGS.saveVideo = True. I cannot see the saved video with tracked bounding boxes in it.

**Comment by seovchinnikov** [comment]
Did you checkout latest version of repo (merge was 1 day ago)?

**Comment by sathishmanivannan** [comment]
Yes.. I did check the latest version, only one file in darkflow was changed. In Predict.py there were changes which was merged with my local repository. However, the tracked video with the bounding boxes is not saved.

**Comment by bendidi** [comment]
I've pushed I fix for that , it should work now

**Comment by seovchinnikov** [comment]
@bendidi, thank you, my bad
I've replaced self.FLAGS.saveVideo with save flag in my code just before commit assuming it was the same in that context

**Comment by sathishmanivannan** [comment]
Thank you Bendidi and Seovchinnikov . Its working now.

**Comment by agrawalparth08** [comment]
which directory does it get saved?
