### ISSUE TITLE
how to track cars?

### ISSUE THREAD

**Issue by mayidu** [bendidi/Tracking-with-darkflow#21]
hello, I have a work to track people, cars, but deep sort only track people,how to track cars and people at the same time? do you train the model?

**Comment by Hydraz320** [comment]
@bendidi Hi, bendidi. I just tried your words. I guess objects can be tracked should be in the list of coco because we use yolo.weights? But when I track "cellphone", "cup" or something, there's no any rectangle. Thanks a lot.
