### ISSUE TITLE
Why weights event.out.tfevents are getting generated in each run in Tracking-with-darkflow\darkflow\summary\train2

### ISSUE THREAD

**Issue by Jumabek** [bendidi/Tracking-with-darkflow#31]
So I have YOLO detector weights in outside directory which is like 
`FLAGS.load = "E:\\darknet\\backup\\head/head_10000.weights"`

When I execute the tracker by `python run.py`  i am getting new file of size 263MB in 
`E:\code\tensorflow\Tracking-with-darkflow\darkflow\summary\train2`

So quickly it occupies a lot of disk memory:
![untitled](https://user-images.githubusercontent.com/4343873/33748325-b4f6df74-db7c-11e7-8cbc-e9f2aa1b6598.png)

Please feel free to give any suggestions.
Thx,
Jumabek

**Comment by bendidi** [comment]
thanks for the info , I just noticed that I had tf events saved too , I'm planning a major cleaning of all the unused code in this repo in the next days and this should be removed by then

**Comment by Jumabek** [comment]
Okay, looking forward to it!
