### ISSUE TITLE
fatal error: Python.h: No such file or directory compilation terminated. error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by KyrieHee** [bendidi/Tracking-with-darkflow#39]
hello, @bendidi , How can I slove this error, I Have been find some methods to slove it, But it doesn't work?
I'm looking forward you reply. Thank you so much.

**Comment by Karthik777** [comment]
If you've not already solved it. in ubuntu 16.04: run 
sudo apt-get install python3-dev
this should fix it.

**Comment by KyrieHee** [comment]
Thank you very much, I have slove it.

At 2018-01-23 09:42:00, "Karthik777" <notifications@github.com> wrote:


If you've not already solved it. in ubuntu 16.04: run
sudo apt-get install python3-dev
this should fix it.

**Comment by JanisSharma** [comment]
On Ubuntu, I was running Python 3 and I had to install

sudo apt-get install python3-dev
If you want to use a version of Python that is not linked to python3, install the associated python3.x-dev package. For example:

sudo apt-get install python3.5-dev

Find All solutions [Here](https://icetutor.com/question/fatal-error-python-h-no-such-file-or-directory)
