### ISSUE TITLE
Getting all detections

### ISSUE THREAD

**Issue by arevel190** [bendidi/Tracking-with-darkflow#4]
Hi,

I would like to know if there is a way to get the other detections as well while getting the people count? I am interested in having a way to get info on the context (no need to be tracked), as well as the unique number of people.

Thanks a lot for your help.

**Comment by bendidi** [comment]
to get all detection + the people tracking,  you can just change this [line](https://github.com/bendidi/darkflow/blob/3bedc08da2faf8d3f4fce057d94c177638940da1/darkflow/net/yolov2/predict.py#L97) in darkflow to something like this : 
```
if self.FLAGS.trackObj != mess :
       cv2.rectangle(imgcv,
			(left, top), (right, bot),
			colors[max_indx], thick)
       cv2.putText(imgcv, mess, (left, top - 12),
			0, 1e-3 * h, colors[max_indx],thick//3)
       continue
```

it will draw the other objects in the image as well.

**Comment by arevel190** [comment]
@bendidi Awesome, thanks. Also, is there a way to output in real time (via txt or csv file) the last ID number detected?

**Comment by bendidi** [comment]
here is the [line](https://github.com/bendidi/darkflow/blob/3bedc08da2faf8d3f4fce057d94c177638940da1/darkflow/net/yolov2/predict.py#L133) where it writes to a csv each new box ID+ frame number + box coordinate in pixels 

and as I've said [here](https://github.com/bendidi/Tracking-with-darkflow/issues/2) in one of my answers : 

> you can set the csv FLAG to true it will write at run time the ID number and the corresponding box in a csv file as mentioned in ReadMe :
> 
> csv : save csv file of detections in the format (frame_id,object_id,x,y,w,h)

**Comment by arevel190** [comment]
@bendidi Thanks again for your prompt reply. I tested this solution, but the csv table is only populated after the program has been stopped. I meant to output real time data, like a stream of values or a csv file that is constantly being populated by the new IDs.

**Comment by bendidi** [comment]
it should be fixed with the last commit :+1:

**Comment by arevel190** [comment]
@bendidi For some reason after your update I am getting a 404 error on the github repo, and it is not updating. Once again thank you very much!

**Comment by arevel190** [comment]
I just double checked and the folder is up again. Now there is another error that is being generated:

_Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from darkflow.darkflow.net.build import TFNet
  File "/Users/pedareva1/Tracking-with-darkflow/darkflow/darkflow/net/build.py", line 7, in <module>
    from .framework import create_framework
  File "/Users/pedareva1/Tracking-with-darkflow/darkflow/darkflow/net/framework.py", line 2, in <module>
    from . import yolov2
  File "/Users/pedareva1/Tracking-with-darkflow/darkflow/darkflow/net/yolov2/__init__.py", line 2, in <module>
    from . import predict
  File "/Users/pedareva1/Tracking-with-darkflow/darkflow/darkflow/net/yolov2/predict.py", line 134
    csv_file.flush()
                   ^
TabError: inconsistent use of tabs and spaces in indentation_

(Sorry for asking too many questions).

**Comment by arevel190** [comment]
I just checked and could solve the error by converting indentation to spaces. Now another error pops up:

_Traceback (most recent call last):
  File "run.py", line 27, in <module>
    tfnet.camera()
  File "/home/pedareva1/Tracking-with-darkflow/darkflow/darkflow/net/help.py", line 107, in camera
    writer.writerow(['frame_id', 'track_id' , 'x', 'y', 'w', 'h'])
TypeError: a bytes-like object is required, not 'str'_

I would really appreciate your help with this.

**Comment by bendidi** [comment]
in line 106 of darkflow/darkflow/net/help.py , just change the 'wb' to 'w' , I'll make the change in the repo later 

It's a problem that happens when using python 3 , when I tested last time it was with python 2 ^^

**Comment by arevel190** [comment]
@bendidi Awesome, thanks a lot!
