### ISSUE TITLE
can't track the objects when I use the sort

### ISSUE THREAD

**Issue by Silencesss** [bendidi/Tracking-with-darkflow#40]
when i use the sort ,FLAGS.track =True,FLAGS.BK_MOG = False ,it can't show the tracking boxes in the video, but when i  set  FLAGS.track =False and FLAGS.BK_MOG = False , it can show the darkflow detecting boxes, when I set FLAGS.track =True and FLAGS.BK_MOG =True,it can show same error boxes,  so I wonder the code of sort  doesn't receive the detecting boxes of darkflow or not ,when I use the deep_sort ,It can work. is there some problems of the code  of sort-with-darkflow?

**Comment by Silencesss** [comment]
I solve it

**Comment by ZhihongChen123** [comment]
Hello,I also have this problem. How did you solve it?Thank you very much! @Silencesss

**Comment by Urviagrawal** [comment]
Hey @Silencesss  can you please tell me how did you solved this problem?

**Comment by Silencesss** [comment]
注释掉Tracking-with-darkflow/darkflow/net/yolov2/predict.py文件中的第100行和101行
#if mess not in self.FLAGS.trackObj :
# continue
这两行注释掉就可以了 @ZhihongChen123 @Urviagrawal

**Comment by Urviagrawal** [comment]
@ZhihongChen123 No darkflow does not support YOLOv3 yet. I have tried running it using darknet and its working well.

**Comment by Urviagrawal** [comment]
@ZhihongChen123 no still I am getting some unwanted tracking boxes and not the actual detections even after commenting lines 100 and 101 as said by @Silencesss
