### ISSUE TITLE
new trained deep_sort WARNING: Failed to extract image patch

### ISSUE THREAD

**Issue by uwmyuan** [bendidi/Tracking-with-darkflow#58]
Hi @bendidi,
Since the authors of `deep_sort` have published their training code, I'm able to fine-tune the `deep_sort` weights with a UAV dataset. However, when testing the newly-trained weights, I got no objects tracked in the video and ` WARNING: Failed to extract image patch`. More details: 
```
Loading from .pb and .meta
Running entirely on CPU
Press [ESC] to quit demo
1.922 FPS
WARNING: Failed to extract image patch: [3662 1809 3662 1809].
WARNING: Failed to extract image patch: [3419 1796 3419 1796].
WARNING: Failed to extract image patch: [3417 1772 3417 1772].
WARNING: Failed to extract image patch: [2912 1762 2912 1762].
WARNING: Failed to extract image patch: [3087 1751 3087 1751].
WARNING: Failed to extract image patch: [2930 1738 2930 1738].
WARNING: Failed to extract image patch: [2985 1691 2985 1691].
WARNING: Failed to extract image patch: [2875 1680 2875 1680].
WARNING: Failed to extract image patch: [2851 1623 2851 1623].
WARNING: Failed to extract image patch: [3301 1600 3301 1600].
WARNING: Failed to extract image patch: [3629 1197 3629 1197].
WARNING: Failed to extract image patch: [2840 1169 2840 1169].
WARNING: Failed to extract image patch: [3515 1076 3515 1076].
WARNING: Failed to extract image patch: [3217  992 3217  992].
WARNING: Failed to extract image patch: [3097  873 3097  873].
WARNING: Failed to extract image patch: [2773  855 2773  855].
WARNING: Failed to extract image patch: [3660 1809 3660 1809].
WARNING: Failed to extract image patch: [3418 1796 3418 1796].
WARNING: Failed to extract image patch: [3332 1780 3332 1780].
WARNING: Failed to extract image patch: [3652 1778 3652 1778].
WARNING: Failed to extract image patch: [3067 1772 3067 1772].
WARNING: Failed to extract image patch: [3404 1766 3404 1766].
WARNING: Failed to extract image patch: [2914 1761 2914 1761].
WARNING: Failed to extract image patch: [3079 1750 3079 1750].
WARNING: Failed to extract image patch: [3297 1600 3297 1600].
WARNING: Failed to extract image patch: [3195 1120 3195 1120].
WARNING: Failed to extract image patch: [3330 1066 3330 1066].
WARNING: Failed to extract image patch: [2830 1065 2830 1065].
WARNING: Failed to extract image patch: [3759  885 3759  885].
WARNING: Failed to extract image patch: [2770  855 2770  855].
WARNING: Failed to extract image patch: [2768  855 2768  855].
...
```
Do you have any clue about this error? Thanks a lot.

**Comment by ZhihongChen123** [comment]
Are you still working on this dataset? I am also studying Stanford drone data sets for detection tracking，can you add my QQ(993573021) for further communicaition? Thank you very much.  @uwmyuan

**Comment by suyashhchougule** [comment]
> Hi @bendidi,
> Since the authors of `deep_sort` have published their training code, I'm able to fine-tune the `deep_sort` weights with a UAV dataset. However, when testing the newly-trained weights, I got no objects tracked in the video and ` WARNING: Failed to extract image patch`. More details:
> 
> ```
> Loading from .pb and .meta
> Running entirely on CPU
> Press [ESC] to quit demo
> 1.922 FPS
> WARNING: Failed to extract image patch: [3662 1809 3662 1809].
> WARNING: Failed to extract image patch: [3419 1796 3419 1796].
> WARNING: Failed to extract image patch: [3417 1772 3417 1772].
> WARNING: Failed to extract image patch: [2912 1762 2912 1762].
> WARNING: Failed to extract image patch: [3087 1751 3087 1751].
> WARNING: Failed to extract image patch: [2930 1738 2930 1738].
> WARNING: Failed to extract image patch: [2985 1691 2985 1691].
> WARNING: Failed to extract image patch: [2875 1680 2875 1680].
> WARNING: Failed to extract image patch: [2851 1623 2851 1623].
> WARNING: Failed to extract image patch: [3301 1600 3301 1600].
> WARNING: Failed to extract image patch: [3629 1197 3629 1197].
> WARNING: Failed to extract image patch: [2840 1169 2840 1169].
> WARNING: Failed to extract image patch: [3515 1076 3515 1076].
> WARNING: Failed to extract image patch: [3217  992 3217  992].
> WARNING: Failed to extract image patch: [3097  873 3097  873].
> WARNING: Failed to extract image patch: [2773  855 2773  855].
> WARNING: Failed to extract image patch: [3660 1809 3660 1809].
> WARNING: Failed to extract image patch: [3418 1796 3418 1796].
> WARNING: Failed to extract image patch: [3332 1780 3332 1780].
> WARNING: Failed to extract image patch: [3652 1778 3652 1778].
> WARNING: Failed to extract image patch: [3067 1772 3067 1772].
> WARNING: Failed to extract image patch: [3404 1766 3404 1766].
> WARNING: Failed to extract image patch: [2914 1761 2914 1761].
> WARNING: Failed to extract image patch: [3079 1750 3079 1750].
> WARNING: Failed to extract image patch: [3297 1600 3297 1600].
> WARNING: Failed to extract image patch: [3195 1120 3195 1120].
> WARNING: Failed to extract image patch: [3330 1066 3330 1066].
> WARNING: Failed to extract image patch: [2830 1065 2830 1065].
> WARNING: Failed to extract image patch: [3759  885 3759  885].
> WARNING: Failed to extract image patch: [2770  855 2770  855].
> WARNING: Failed to extract image patch: [2768  855 2768  855].
> ...
> ```
> 
> Do you have any clue about this error? Thanks a lot.
for anyone facing this error ,
The detection model that you are using should have the bounding box output like this bbox= [min_x, min_y  width, height]

**Comment by suyashhchougule** [comment]
for anyone facing this error ,
The detection model that you are using should have the bounding box output like this bbox= [min_x, min_y width, height]

**Comment by stap1e** [comment]
求问如何解决
