### ISSUE TITLE
Getting csv of other predictions

### ISSUE THREAD

**Issue by arevel190** [bendidi/Tracking-with-darkflow#7]
Hi,

I wanted to know if it is possible to get a real time csv file (no need to be tracked) of all the objects darkflow detects. This would be super useful for context analysis.

Thank you very much!

**Comment by bendidi** [comment]
you can achieve that by modifying [predict.py](https://github.com/bendidi/darkflow/blob/5ab192c032be918f868019f73e914e2ef0b8675b/darkflow/net/yolov2/predict.py)  : 
you can get all the detection from this [line](https://github.com/bendidi/darkflow/blob/5ab192c032be918f868019f73e914e2ef0b8675b/darkflow/net/yolov2/predict.py#L96)  and you just need to write them to csv like in [here](https://github.com/bendidi/darkflow/blob/5ab192c032be918f868019f73e914e2ef0b8675b/darkflow/net/yolov2/predict.py#L96)

**Comment by arevel190** [comment]
@bendidi Thank you very much!
