### ISSUE TITLE
When  I run the code "python run.py" ，there is an error . how can I solve it?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [bendidi/Tracking-with-darkflow#83]
when I user GPU, it occurs: 
F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

but when I use CPU, it can correctly run.

**Comment by zhangjinjing3** [comment]
你好，我仍然没有解决在自己的视频上测试的问题，非常着急，可以加qq向您请教下吗？我qq253467672
