### ISSUE TITLE
Excuse me? Can this code use pb files?

### ISSUE THREAD

**Issue by ss199302** [bendidi/Tracking-with-darkflow#93]
@bendidi

**Comment by obendidi** [comment]
Hi, 
This code supports models trained with the original darkflow module : https://github.com/thtrieu/darkflow 

it will generate a `.pb` and `.meta` files , that you need to specify here https://github.com/bendidi/Tracking-with-darkflow/blob/master/run.py#L11 (and comment the lines 9 and 10)

**Comment by ss199302** [comment]
@bendidi  Thanks!
